using System.ComponentModel.DataAnnotations;
using OMS.Core.Common;

namespace OMS.Core.Models;

[GenerateSerializer]
[Alias("NewOrder")]
public class NewOrder
{
    [Key]
    [Id(10)]
    public int NewOrderID { get; set; }

    // PlatformOrderID generated by platform of record
    [Id(11)]
    public int PlatformOrderID { get; set; }

    // In the case of NinjaTrader as the execution platform, this would be the filled order ID returned on execution
    [Id(1)]
    public string? UserName { get; set; }
    
    [Id(2)]
    public int UserID { get; set; }
    
    [Id(3)]
    public int UserGroup { get; set; }

    // Token for successful trader authentication
    [Id(4)]
    public int AuthToken { get; set; }
    
    [Id(5)]
    public required string Instrument { get; set; }
    
    [Id(6)]
    public double OrderPX { get; set; }

    // Market, Limit, Stop
    [Id(7)]
    public OrderType OrderType { get; set; }

    // Buy, Sell
    [Id(8)]
    public OrderAction OrderAction { get; set; }
    
    [Id(9)]
    public int Quantity { get; set; }
}